version: "3.8"

services:
  web:
    build: .
    ports:
      - "5001:5000" # Change the host port to 5001 if 5000 is occupied
    env_file:
      - .env # Specify the environment file to use
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "./wait-for-it.sh db:3306 -- 
      flask db upgrade &&
      flask run --host=0.0.0.0 --port=5000"  # Flask will run on port 5000 inside the container

  db:
    image: mysql:8.0
    env_file:
      - .env # Specify the environment file to use for MySQL settings
    ports:
      - "3307:3306" # Use 3307 on the host machine if 3306 is in use
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
