rule_files:
  - "alert.rules.yml"

scrape_configs:
  - job_name: 'python_app'
    static_configs:
      - targets: ['localhost:6000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["localhost:9093"]
