"""Ensure date_last_used column exists

Revision ID: 0066664c12dd
Revises: 87f471c5b7d7
Create Date: 2024-08-14 01:53:41.867607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0066664c12dd'
down_revision = '87f471c5b7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_last_used', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('url_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('last_used_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=False)

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('url_ibfk_1', 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('date_last_used')

    # ### end Alembic commands ###
